# Generated by Django 5.0.7 on 2024-08-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='items_images'),
        ),
    ]
